[workflow]
version = 1
start_node_id = "start"

[[workflow.nodes]]
id = "start"
type = "start"

[workflow.nodes.position]
x = 80.0
y = 180.0

[[workflow.nodes]]
id = "match-1"
type = "match"

[workflow.nodes.position]
x = 236.42857142857144
y = 260.0

[workflow.nodes.match]
plugin_id = "match-evaluator"
timeout_ms = 250
max_memory_bytes = 16777216
granted_capabilities = ["log"]
read_dirs = []
write_dirs = []
allowed_hosts = []
fallback_node_id = "end"

[workflow.nodes.match.config]

[[workflow.nodes.match.branches]]
id = "chat-api"
expr = 'method == "POST" && path == "/v1/chat/completions"'
target_node_id = "wasm_plugin-6"

[[workflow.nodes]]
id = "select-chat-model"
type = "wasm_plugin"

[workflow.nodes.position]
x = 735.9885960314949
y = -286.849879003998

[workflow.nodes.wasm_plugin]
plugin_id = "select-model"
timeout_ms = 250
max_memory_bytes = 16777216
granted_capabilities = ["log"]
read_dirs = []
write_dirs = []
allowed_hosts = []

[workflow.nodes.wasm_plugin.config]
model_id = "gpt-5.3-codex"
provider_id = "glm-inner"

[[workflow.nodes]]
id = "finalize-response"
type = "wasm_plugin"

[workflow.nodes.position]
x = 877.1428571428571
y = 54.28571428571426

[workflow.nodes.wasm_plugin]
plugin_id = "workflow-transform"
timeout_ms = 250
max_memory_bytes = 16777216
granted_capabilities = ["log"]
read_dirs = []
write_dirs = []
allowed_hosts = []

[workflow.nodes.wasm_plugin.config]
log_message = "matched=${ctx.match.last_branch} result=${ctx.match.last_result} path=${path}"

[[workflow.nodes.wasm_plugin.config.set_headers]]
name = "x-route-engine"
op = "set"
value = "match"

[[workflow.nodes]]
id = "end"
type = "end"

[workflow.nodes.position]
x = 1160.0
y = 180.0

[[workflow.nodes]]
id = "wasm_plugin-6"
type = "wasm_plugin"

[workflow.nodes.position]
x = 405.34555197367183
y = -69.36392883192728

[workflow.nodes.wasm_plugin]
plugin_id = "set-header"
timeout_ms = 20
max_memory_bytes = 16777216
granted_capabilities = ["log"]
read_dirs = []
write_dirs = []
allowed_hosts = []

[[workflow.nodes.wasm_plugin.config.set_headers]]
name = "Authorization"
op = "set"
value = "Bearer sk-zsBBXuucIiULkz74rTHVmiMLPWCSYl32"

[[workflow.edges]]
id = "start-next"
source = "start"
target = "match-1"

[[workflow.edges]]
id = "select-chat-model-next"
source = "select-chat-model"
target = "finalize-response"

[[workflow.edges]]
id = "finalize-response-next"
source = "finalize-response"
target = "end"

[[workflow.edges]]
id = "match-1-match:fallback"
source = "match-1"
target = "end"
source_handle = "match:fallback"

[[workflow.edges]]
id = "match-1-match:chat-api"
source = "match-1"
target = "wasm_plugin-6"
source_handle = "match:chat-api"

[[workflow.edges]]
id = "wasm_plugin-6-default"
source = "wasm_plugin-6"
target = "select-chat-model"
source_handle = "default"
