[workflow]
version = 1
start_node_id = "start"

[[workflow.nodes]]
id = "start"
type = "start"

[workflow.nodes.position]
x = -63.18296645533293
y = 88.4561530374661

[[workflow.nodes]]
id = "wasm_plugin-2"
type = "wasm_plugin"

[workflow.nodes.position]
x = 352.14285714285717
y = -103.35714285714286

[workflow.nodes.wasm_plugin]
plugin_id = "intent-classifier"
timeout_ms = 20
max_memory_bytes = 16777216
granted_capabilities = ["log"]
read_dirs = []
write_dirs = []
allowed_hosts = []

[workflow.nodes.wasm_plugin.config]

[[workflow.nodes]]
id = "log-3"
type = "log"

[workflow.nodes.position]
x = 918.735413287674
y = 107.22739856616096

[workflow.nodes.log]
message = """
route=${ctx.route_hint} model=${ctx.model.id}
111"""

[[workflow.nodes]]
id = "end-4"
type = "end"

[workflow.nodes.position]
x = 1198.026333901773
y = 337.88557180964597

[[workflow.nodes]]
id = "log-5"
type = "log"

[workflow.nodes.position]
x = 802.0168195981996
y = 510.1844482083937

[workflow.nodes.log]
message = """
route=${ctx.route_hint} model=${ctx.model.id}
222"""

[[workflow.edges]]
id = "start-next"
source = "start"
target = "wasm_plugin-2"

[[workflow.edges]]
id = "wasm_plugin-2-default"
source = "wasm_plugin-2"
target = "log-3"
source_handle = "default"

[[workflow.edges]]
id = "log-3-next"
source = "log-3"
target = "end-4"

[[workflow.edges]]
id = "wasm_plugin-2-chat"
source = "wasm_plugin-2"
target = "log-5"
source_handle = "chat"

[[workflow.edges]]
id = "log-5-next"
source = "log-5"
target = "end-4"
