// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod proxy_tools {
        pub mod proxy_node_plugin {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod node_plugin {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Clone)]
                pub struct RequestHeader {
                    pub name: _rt::String,
                    pub value: _rt::String,
                }
                impl ::core::fmt::Debug for RequestHeader {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("RequestHeader")
                            .field("name", &self.name)
                            .field("value", &self.value)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct ContextEntry {
                    pub key: _rt::String,
                    pub value: _rt::String,
                }
                impl ::core::fmt::Debug for ContextEntry {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ContextEntry")
                            .field("key", &self.key)
                            .field("value", &self.value)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct JsonDocument {
                    pub json: _rt::String,
                }
                impl ::core::fmt::Debug for JsonDocument {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("JsonDocument").field("json", &self.json).finish()
                    }
                }
                #[derive(Clone)]
                pub enum ContextPatchOp {
                    Set(ContextEntry),
                    Remove(_rt::String),
                }
                impl ::core::fmt::Debug for ContextPatchOp {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            ContextPatchOp::Set(e) => {
                                f.debug_tuple("ContextPatchOp::Set").field(e).finish()
                            }
                            ContextPatchOp::Remove(e) => {
                                f.debug_tuple("ContextPatchOp::Remove").field(e).finish()
                            }
                        }
                    }
                }
                #[derive(Clone)]
                pub struct ContextPatch {
                    pub ops: _rt::Vec<ContextPatchOp>,
                }
                impl ::core::fmt::Debug for ContextPatch {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ContextPatch").field("ops", &self.ops).finish()
                    }
                }
                #[derive(Clone)]
                pub enum HeaderOp {
                    Set(RequestHeader),
                    Append(RequestHeader),
                    Remove(_rt::String),
                }
                impl ::core::fmt::Debug for HeaderOp {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            HeaderOp::Set(e) => {
                                f.debug_tuple("HeaderOp::Set").field(e).finish()
                            }
                            HeaderOp::Append(e) => {
                                f.debug_tuple("HeaderOp::Append").field(e).finish()
                            }
                            HeaderOp::Remove(e) => {
                                f.debug_tuple("HeaderOp::Remove").field(e).finish()
                            }
                        }
                    }
                }
                #[derive(Clone)]
                pub struct PathRewrite {
                    pub path: _rt::String,
                }
                impl ::core::fmt::Debug for PathRewrite {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("PathRewrite").field("path", &self.path).finish()
                    }
                }
                #[derive(Clone)]
                pub struct NextPort {
                    pub port: _rt::String,
                }
                impl ::core::fmt::Debug for NextPort {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("NextPort").field("port", &self.port).finish()
                    }
                }
                #[derive(Clone, Copy)]
                pub enum LogLevel {
                    Debug,
                    Info,
                    Warn,
                    Error,
                }
                impl ::core::fmt::Debug for LogLevel {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            LogLevel::Debug => f.debug_tuple("LogLevel::Debug").finish(),
                            LogLevel::Info => f.debug_tuple("LogLevel::Info").finish(),
                            LogLevel::Warn => f.debug_tuple("LogLevel::Warn").finish(),
                            LogLevel::Error => f.debug_tuple("LogLevel::Error").finish(),
                        }
                    }
                }
                #[derive(Clone)]
                pub struct LogEntry {
                    pub level: LogLevel,
                    pub message: _rt::String,
                }
                impl ::core::fmt::Debug for LogEntry {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("LogEntry")
                            .field("level", &self.level)
                            .field("message", &self.message)
                            .finish()
                    }
                }
                #[derive(Clone, Copy)]
                pub enum CapabilityKind {
                    Log,
                    Fs,
                    Network,
                }
                impl ::core::fmt::Debug for CapabilityKind {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            CapabilityKind::Log => {
                                f.debug_tuple("CapabilityKind::Log").finish()
                            }
                            CapabilityKind::Fs => {
                                f.debug_tuple("CapabilityKind::Fs").finish()
                            }
                            CapabilityKind::Network => {
                                f.debug_tuple("CapabilityKind::Network").finish()
                            }
                        }
                    }
                }
                #[derive(Clone)]
                pub struct CapabilityDeclaration {
                    pub kind: CapabilityKind,
                    pub required: bool,
                    pub scope: Option<_rt::String>,
                    pub description: _rt::String,
                }
                impl ::core::fmt::Debug for CapabilityDeclaration {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("CapabilityDeclaration")
                            .field("kind", &self.kind)
                            .field("required", &self.required)
                            .field("scope", &self.scope)
                            .field("description", &self.description)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct CapabilityGrant {
                    pub kind: CapabilityKind,
                    pub allowed: bool,
                    pub scope: Option<_rt::String>,
                }
                impl ::core::fmt::Debug for CapabilityGrant {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("CapabilityGrant")
                            .field("kind", &self.kind)
                            .field("allowed", &self.allowed)
                            .field("scope", &self.scope)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct PluginManifest {
                    pub id: _rt::String,
                    pub name: _rt::String,
                    pub version: _rt::String,
                    pub description: _rt::String,
                    pub supported_output_ports: _rt::Vec<_rt::String>,
                    pub default_config_schema_hints: Option<JsonDocument>,
                    pub capabilities: _rt::Vec<CapabilityDeclaration>,
                }
                impl ::core::fmt::Debug for PluginManifest {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("PluginManifest")
                            .field("id", &self.id)
                            .field("name", &self.name)
                            .field("version", &self.version)
                            .field("description", &self.description)
                            .field(
                                "supported-output-ports",
                                &self.supported_output_ports,
                            )
                            .field(
                                "default-config-schema-hints",
                                &self.default_config_schema_hints,
                            )
                            .field("capabilities", &self.capabilities)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct NodeConfig {
                    pub manifest: PluginManifest,
                    pub grants: _rt::Vec<CapabilityGrant>,
                    pub config: Option<JsonDocument>,
                }
                impl ::core::fmt::Debug for NodeConfig {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("NodeConfig")
                            .field("manifest", &self.manifest)
                            .field("grants", &self.grants)
                            .field("config", &self.config)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct ExecuteInput {
                    pub request_method: _rt::String,
                    pub current_path: _rt::String,
                    pub request_headers: _rt::Vec<RequestHeader>,
                    pub workflow_context: _rt::Vec<ContextEntry>,
                    pub selected_provider_id: _rt::String,
                    pub selected_model_id: _rt::String,
                    pub node_config: NodeConfig,
                }
                impl ::core::fmt::Debug for ExecuteInput {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ExecuteInput")
                            .field("request-method", &self.request_method)
                            .field("current-path", &self.current_path)
                            .field("request-headers", &self.request_headers)
                            .field("workflow-context", &self.workflow_context)
                            .field("selected-provider-id", &self.selected_provider_id)
                            .field("selected-model-id", &self.selected_model_id)
                            .field("node-config", &self.node_config)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct ExecuteOutput {
                    pub context_patch: Option<ContextPatch>,
                    pub header_ops: _rt::Vec<HeaderOp>,
                    pub path_rewrite: Option<PathRewrite>,
                    pub next_port: Option<NextPort>,
                    pub logs: _rt::Vec<LogEntry>,
                }
                impl ::core::fmt::Debug for ExecuteOutput {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ExecuteOutput")
                            .field("context-patch", &self.context_patch)
                            .field("header-ops", &self.header_ops)
                            .field("path-rewrite", &self.path_rewrite)
                            .field("next-port", &self.next_port)
                            .field("logs", &self.logs)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub enum ExecuteError {
                    Denied(_rt::String),
                    InvalidInput(_rt::String),
                    Failed(_rt::String),
                }
                impl ::core::fmt::Debug for ExecuteError {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            ExecuteError::Denied(e) => {
                                f.debug_tuple("ExecuteError::Denied").field(e).finish()
                            }
                            ExecuteError::InvalidInput(e) => {
                                f.debug_tuple("ExecuteError::InvalidInput")
                                    .field(e)
                                    .finish()
                            }
                            ExecuteError::Failed(e) => {
                                f.debug_tuple("ExecuteError::Failed").field(e).finish()
                            }
                        }
                    }
                }
                impl ::core::fmt::Display for ExecuteError {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        write!(f, "{:?}", self)
                    }
                }
                impl std::error::Error for ExecuteError {}
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_execute_cabi<T: Guest>(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len2 = l1;
                    let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
                    let l3 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l4 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len5 = l4;
                    let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                    let l6 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l7 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base14 = l6;
                    let len14 = l7;
                    let mut result14 = _rt::Vec::with_capacity(len14);
                    for i in 0..len14 {
                        let base = base14
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e14 = {
                            let l8 = *base.add(0).cast::<*mut u8>();
                            let l9 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len10 = l9;
                            let bytes10 = _rt::Vec::from_raw_parts(
                                l8.cast(),
                                len10,
                                len10,
                            );
                            let l11 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l12 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len13 = l12;
                            let bytes13 = _rt::Vec::from_raw_parts(
                                l11.cast(),
                                len13,
                                len13,
                            );
                            RequestHeader {
                                name: _rt::string_lift(bytes10),
                                value: _rt::string_lift(bytes13),
                            }
                        };
                        result14.push(e14);
                    }
                    _rt::cabi_dealloc(
                        base14,
                        len14 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l15 = *arg0
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l16 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base23 = l15;
                    let len23 = l16;
                    let mut result23 = _rt::Vec::with_capacity(len23);
                    for i in 0..len23 {
                        let base = base23
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e23 = {
                            let l17 = *base.add(0).cast::<*mut u8>();
                            let l18 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len19 = l18;
                            let bytes19 = _rt::Vec::from_raw_parts(
                                l17.cast(),
                                len19,
                                len19,
                            );
                            let l20 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l21 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len22 = l21;
                            let bytes22 = _rt::Vec::from_raw_parts(
                                l20.cast(),
                                len22,
                                len22,
                            );
                            ContextEntry {
                                key: _rt::string_lift(bytes19),
                                value: _rt::string_lift(bytes22),
                            }
                        };
                        result23.push(e23);
                    }
                    _rt::cabi_dealloc(
                        base23,
                        len23 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l24 = *arg0
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l25 = *arg0
                        .add(9 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len26 = l25;
                    let bytes26 = _rt::Vec::from_raw_parts(l24.cast(), len26, len26);
                    let l27 = *arg0
                        .add(10 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l28 = *arg0
                        .add(11 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len29 = l28;
                    let bytes29 = _rt::Vec::from_raw_parts(l27.cast(), len29, len29);
                    let l30 = *arg0
                        .add(12 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l31 = *arg0
                        .add(13 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len32 = l31;
                    let bytes32 = _rt::Vec::from_raw_parts(l30.cast(), len32, len32);
                    let l33 = *arg0
                        .add(14 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l34 = *arg0
                        .add(15 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len35 = l34;
                    let bytes35 = _rt::Vec::from_raw_parts(l33.cast(), len35, len35);
                    let l36 = *arg0
                        .add(16 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l37 = *arg0
                        .add(17 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len38 = l37;
                    let bytes38 = _rt::Vec::from_raw_parts(l36.cast(), len38, len38);
                    let l39 = *arg0
                        .add(18 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l40 = *arg0
                        .add(19 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len41 = l40;
                    let bytes41 = _rt::Vec::from_raw_parts(l39.cast(), len41, len41);
                    let l42 = *arg0
                        .add(20 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l43 = *arg0
                        .add(21 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base47 = l42;
                    let len47 = l43;
                    let mut result47 = _rt::Vec::with_capacity(len47);
                    for i in 0..len47 {
                        let base = base47
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e47 = {
                            let l44 = *base.add(0).cast::<*mut u8>();
                            let l45 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len46 = l45;
                            let bytes46 = _rt::Vec::from_raw_parts(
                                l44.cast(),
                                len46,
                                len46,
                            );
                            _rt::string_lift(bytes46)
                        };
                        result47.push(e47);
                    }
                    _rt::cabi_dealloc(
                        base47,
                        len47 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l48 = i32::from(
                        *arg0.add(22 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    let l52 = *arg0
                        .add(25 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l53 = *arg0
                        .add(26 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base64 = l52;
                    let len64 = l53;
                    let mut result64 = _rt::Vec::with_capacity(len64);
                    for i in 0..len64 {
                        let base = base64
                            .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                        let e64 = {
                            let l54 = i32::from(*base.add(0).cast::<u8>());
                            let v55 = match l54 {
                                0 => CapabilityKind::Log,
                                1 => CapabilityKind::Fs,
                                n => {
                                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                                    CapabilityKind::Network
                                }
                            };
                            let l56 = i32::from(*base.add(1).cast::<u8>());
                            let l57 = i32::from(
                                *base.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            let l61 = *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l62 = *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len63 = l62;
                            let bytes63 = _rt::Vec::from_raw_parts(
                                l61.cast(),
                                len63,
                                len63,
                            );
                            CapabilityDeclaration {
                                kind: v55,
                                required: _rt::bool_lift(l56 as u8),
                                scope: match l57 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l58 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l59 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len60 = l59;
                                            let bytes60 = _rt::Vec::from_raw_parts(
                                                l58.cast(),
                                                len60,
                                                len60,
                                            );
                                            _rt::string_lift(bytes60)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                description: _rt::string_lift(bytes63),
                            }
                        };
                        result64.push(e64);
                    }
                    _rt::cabi_dealloc(
                        base64,
                        len64 * (6 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l65 = *arg0
                        .add(27 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l66 = *arg0
                        .add(28 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base74 = l65;
                    let len74 = l66;
                    let mut result74 = _rt::Vec::with_capacity(len74);
                    for i in 0..len74 {
                        let base = base74
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e74 = {
                            let l67 = i32::from(*base.add(0).cast::<u8>());
                            let v68 = match l67 {
                                0 => CapabilityKind::Log,
                                1 => CapabilityKind::Fs,
                                n => {
                                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                                    CapabilityKind::Network
                                }
                            };
                            let l69 = i32::from(*base.add(1).cast::<u8>());
                            let l70 = i32::from(
                                *base.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            CapabilityGrant {
                                kind: v68,
                                allowed: _rt::bool_lift(l69 as u8),
                                scope: match l70 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l71 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l72 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len73 = l72;
                                            let bytes73 = _rt::Vec::from_raw_parts(
                                                l71.cast(),
                                                len73,
                                                len73,
                                            );
                                            _rt::string_lift(bytes73)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                            }
                        };
                        result74.push(e74);
                    }
                    _rt::cabi_dealloc(
                        base74,
                        len74 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l75 = i32::from(
                        *arg0.add(29 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    let result79 = T::execute(ExecuteInput {
                        request_method: _rt::string_lift(bytes2),
                        current_path: _rt::string_lift(bytes5),
                        request_headers: result14,
                        workflow_context: result23,
                        selected_provider_id: _rt::string_lift(bytes26),
                        selected_model_id: _rt::string_lift(bytes29),
                        node_config: NodeConfig {
                            manifest: PluginManifest {
                                id: _rt::string_lift(bytes32),
                                name: _rt::string_lift(bytes35),
                                version: _rt::string_lift(bytes38),
                                description: _rt::string_lift(bytes41),
                                supported_output_ports: result47,
                                default_config_schema_hints: match l48 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l49 = *arg0
                                                .add(23 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l50 = *arg0
                                                .add(24 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let len51 = l50;
                                            let bytes51 = _rt::Vec::from_raw_parts(
                                                l49.cast(),
                                                len51,
                                                len51,
                                            );
                                            JsonDocument {
                                                json: _rt::string_lift(bytes51),
                                            }
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                capabilities: result64,
                            },
                            grants: result74,
                            config: match l75 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let l76 = *arg0
                                            .add(30 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l77 = *arg0
                                            .add(31 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len78 = l77;
                                        let bytes78 = _rt::Vec::from_raw_parts(
                                            l76.cast(),
                                            len78,
                                            len78,
                                        );
                                        JsonDocument {
                                            json: _rt::string_lift(bytes78),
                                        }
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                        },
                    });
                    _rt::cabi_dealloc(
                        arg0,
                        32 * ::core::mem::size_of::<*const u8>(),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let ptr80 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result79 {
                        Ok(e) => {
                            *ptr80.add(0).cast::<u8>() = (0i32) as u8;
                            let ExecuteOutput {
                                context_patch: context_patch81,
                                header_ops: header_ops81,
                                path_rewrite: path_rewrite81,
                                next_port: next_port81,
                                logs: logs81,
                            } = e;
                            match context_patch81 {
                                Some(e) => {
                                    *ptr80
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let ContextPatch { ops: ops82 } = e;
                                    let vec87 = ops82;
                                    let len87 = vec87.len();
                                    let layout87 = _rt::alloc::Layout::from_size_align_unchecked(
                                        vec87.len() * (5 * ::core::mem::size_of::<*const u8>()),
                                        ::core::mem::size_of::<*const u8>(),
                                    );
                                    let result87 = if layout87.size() != 0 {
                                        let ptr = _rt::alloc::alloc(layout87).cast::<u8>();
                                        if ptr.is_null() {
                                            _rt::alloc::handle_alloc_error(layout87);
                                        }
                                        ptr
                                    } else {
                                        ::core::ptr::null_mut()
                                    };
                                    for (i, e) in vec87.into_iter().enumerate() {
                                        let base = result87
                                            .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                        {
                                            match e {
                                                ContextPatchOp::Set(e) => {
                                                    *base.add(0).cast::<u8>() = (0i32) as u8;
                                                    let ContextEntry { key: key83, value: value83 } = e;
                                                    let vec84 = (key83.into_bytes()).into_boxed_slice();
                                                    let ptr84 = vec84.as_ptr().cast::<u8>();
                                                    let len84 = vec84.len();
                                                    ::core::mem::forget(vec84);
                                                    *base
                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>() = len84;
                                                    *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>() = ptr84.cast_mut();
                                                    let vec85 = (value83.into_bytes()).into_boxed_slice();
                                                    let ptr85 = vec85.as_ptr().cast::<u8>();
                                                    let len85 = vec85.len();
                                                    ::core::mem::forget(vec85);
                                                    *base
                                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>() = len85;
                                                    *base
                                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>() = ptr85.cast_mut();
                                                }
                                                ContextPatchOp::Remove(e) => {
                                                    *base.add(0).cast::<u8>() = (1i32) as u8;
                                                    let vec86 = (e.into_bytes()).into_boxed_slice();
                                                    let ptr86 = vec86.as_ptr().cast::<u8>();
                                                    let len86 = vec86.len();
                                                    ::core::mem::forget(vec86);
                                                    *base
                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>() = len86;
                                                    *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>() = ptr86.cast_mut();
                                                }
                                            }
                                        }
                                    }
                                    *ptr80
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len87;
                                    *ptr80
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = result87;
                                }
                                None => {
                                    *ptr80
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            let vec95 = header_ops81;
                            let len95 = vec95.len();
                            let layout95 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec95.len() * (5 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result95 = if layout95.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout95).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout95);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec95.into_iter().enumerate() {
                                let base = result95
                                    .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                {
                                    match e {
                                        HeaderOp::Set(e) => {
                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                            let RequestHeader { name: name88, value: value88 } = e;
                                            let vec89 = (name88.into_bytes()).into_boxed_slice();
                                            let ptr89 = vec89.as_ptr().cast::<u8>();
                                            let len89 = vec89.len();
                                            ::core::mem::forget(vec89);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len89;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr89.cast_mut();
                                            let vec90 = (value88.into_bytes()).into_boxed_slice();
                                            let ptr90 = vec90.as_ptr().cast::<u8>();
                                            let len90 = vec90.len();
                                            ::core::mem::forget(vec90);
                                            *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len90;
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr90.cast_mut();
                                        }
                                        HeaderOp::Append(e) => {
                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                            let RequestHeader { name: name91, value: value91 } = e;
                                            let vec92 = (name91.into_bytes()).into_boxed_slice();
                                            let ptr92 = vec92.as_ptr().cast::<u8>();
                                            let len92 = vec92.len();
                                            ::core::mem::forget(vec92);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len92;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr92.cast_mut();
                                            let vec93 = (value91.into_bytes()).into_boxed_slice();
                                            let ptr93 = vec93.as_ptr().cast::<u8>();
                                            let len93 = vec93.len();
                                            ::core::mem::forget(vec93);
                                            *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len93;
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr93.cast_mut();
                                        }
                                        HeaderOp::Remove(e) => {
                                            *base.add(0).cast::<u8>() = (2i32) as u8;
                                            let vec94 = (e.into_bytes()).into_boxed_slice();
                                            let ptr94 = vec94.as_ptr().cast::<u8>();
                                            let len94 = vec94.len();
                                            ::core::mem::forget(vec94);
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len94;
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = ptr94.cast_mut();
                                        }
                                    }
                                }
                            }
                            *ptr80
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len95;
                            *ptr80
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result95;
                            match path_rewrite81 {
                                Some(e) => {
                                    *ptr80
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let PathRewrite { path: path96 } = e;
                                    let vec97 = (path96.into_bytes()).into_boxed_slice();
                                    let ptr97 = vec97.as_ptr().cast::<u8>();
                                    let len97 = vec97.len();
                                    ::core::mem::forget(vec97);
                                    *ptr80
                                        .add(8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len97;
                                    *ptr80
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr97.cast_mut();
                                }
                                None => {
                                    *ptr80
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match next_port81 {
                                Some(e) => {
                                    *ptr80
                                        .add(9 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let NextPort { port: port98 } = e;
                                    let vec99 = (port98.into_bytes()).into_boxed_slice();
                                    let ptr99 = vec99.as_ptr().cast::<u8>();
                                    let len99 = vec99.len();
                                    ::core::mem::forget(vec99);
                                    *ptr80
                                        .add(11 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len99;
                                    *ptr80
                                        .add(10 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr99.cast_mut();
                                }
                                None => {
                                    *ptr80
                                        .add(9 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            let vec102 = logs81;
                            let len102 = vec102.len();
                            let layout102 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec102.len() * (3 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result102 = if layout102.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout102).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout102);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec102.into_iter().enumerate() {
                                let base = result102
                                    .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let LogEntry { level: level100, message: message100 } = e;
                                    match level100 {
                                        LogLevel::Debug => {
                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                        }
                                        LogLevel::Info => {
                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                        }
                                        LogLevel::Warn => {
                                            *base.add(0).cast::<u8>() = (2i32) as u8;
                                        }
                                        LogLevel::Error => {
                                            *base.add(0).cast::<u8>() = (3i32) as u8;
                                        }
                                    }
                                    let vec101 = (message100.into_bytes()).into_boxed_slice();
                                    let ptr101 = vec101.as_ptr().cast::<u8>();
                                    let len101 = vec101.len();
                                    ::core::mem::forget(vec101);
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len101;
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr101.cast_mut();
                                }
                            }
                            *ptr80
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len102;
                            *ptr80
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result102;
                        }
                        Err(e) => {
                            *ptr80.add(0).cast::<u8>() = (1i32) as u8;
                            match e {
                                ExecuteError::Denied(e) => {
                                    *ptr80
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec103 = (e.into_bytes()).into_boxed_slice();
                                    let ptr103 = vec103.as_ptr().cast::<u8>();
                                    let len103 = vec103.len();
                                    ::core::mem::forget(vec103);
                                    *ptr80
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len103;
                                    *ptr80
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr103.cast_mut();
                                }
                                ExecuteError::InvalidInput(e) => {
                                    *ptr80
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec104 = (e.into_bytes()).into_boxed_slice();
                                    let ptr104 = vec104.as_ptr().cast::<u8>();
                                    let len104 = vec104.len();
                                    ::core::mem::forget(vec104);
                                    *ptr80
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len104;
                                    *ptr80
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr104.cast_mut();
                                }
                                ExecuteError::Failed(e) => {
                                    *ptr80
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                    let vec105 = (e.into_bytes()).into_boxed_slice();
                                    let ptr105 = vec105.as_ptr().cast::<u8>();
                                    let len105 = vec105.len();
                                    ::core::mem::forget(vec105);
                                    *ptr80
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len105;
                                    *ptr80
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr105.cast_mut();
                                }
                            }
                        }
                    };
                    ptr80
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_execute<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l1 {
                                0 => {}
                                _ => {
                                    let l2 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let base11 = l2;
                                    let len11 = l3;
                                    for i in 0..len11 {
                                        let base = base11
                                            .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                        {
                                            let l4 = i32::from(*base.add(0).cast::<u8>());
                                            match l4 {
                                                0 => {
                                                    let l5 = *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l6 = *base
                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    _rt::cabi_dealloc(l5, l6, 1);
                                                    let l7 = *base
                                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l8 = *base
                                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    _rt::cabi_dealloc(l7, l8, 1);
                                                }
                                                _ => {
                                                    let l9 = *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l10 = *base
                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    _rt::cabi_dealloc(l9, l10, 1);
                                                }
                                            }
                                        }
                                    }
                                    _rt::cabi_dealloc(
                                        base11,
                                        len11 * (5 * ::core::mem::size_of::<*const u8>()),
                                        ::core::mem::size_of::<*const u8>(),
                                    );
                                }
                            }
                            let l12 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base25 = l12;
                            let len25 = l13;
                            for i in 0..len25 {
                                let base = base25
                                    .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l14 = i32::from(*base.add(0).cast::<u8>());
                                    match l14 {
                                        0 => {
                                            let l15 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l16 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l15, l16, 1);
                                            let l17 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l18 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l17, l18, 1);
                                        }
                                        1 => {
                                            let l19 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l20 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l19, l20, 1);
                                            let l21 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l22 = *base
                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l21, l22, 1);
                                        }
                                        _ => {
                                            let l23 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l24 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            _rt::cabi_dealloc(l23, l24, 1);
                                        }
                                    }
                                }
                            }
                            _rt::cabi_dealloc(
                                base25,
                                len25 * (5 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l26 = i32::from(
                                *arg0
                                    .add(6 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l26 {
                                0 => {}
                                _ => {
                                    let l27 = *arg0
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l28 = *arg0
                                        .add(8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l27, l28, 1);
                                }
                            }
                            let l29 = i32::from(
                                *arg0
                                    .add(9 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l29 {
                                0 => {}
                                _ => {
                                    let l30 = *arg0
                                        .add(10 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l31 = *arg0
                                        .add(11 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l30, l31, 1);
                                }
                            }
                            let l32 = *arg0
                                .add(12 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l33 = *arg0
                                .add(13 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base36 = l32;
                            let len36 = l33;
                            for i in 0..len36 {
                                let base = base36
                                    .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l34 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l35 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l34, l35, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base36,
                                len36 * (3 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                        _ => {
                            let l37 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l37 {
                                0 => {
                                    let l38 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l39 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l38, l39, 1);
                                }
                                1 => {
                                    let l40 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l41 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l40, l41, 1);
                                }
                                _ => {
                                    let l42 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l43 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l42, l43, 1);
                                }
                            }
                        }
                    }
                }
                pub trait Guest {
                    fn execute(
                        input: ExecuteInput,
                    ) -> Result<ExecuteOutput, ExecuteError>;
                }
                #[doc(hidden)]
                macro_rules! __export_proxy_tools_proxy_node_plugin_node_plugin_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "proxy-tools:proxy-node-plugin/node-plugin@0.1.0#execute")]
                        unsafe extern "C" fn export_execute(arg0 : * mut u8,) -> * mut u8
                        { unsafe { $($path_to_types)*:: _export_execute_cabi::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "cabi_post_proxy-tools:proxy-node-plugin/node-plugin@0.1.0#execute")]
                        unsafe extern "C" fn _post_return_execute(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_execute::<$ty >
                        (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_proxy_tools_proxy_node_plugin_node_plugin_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 14 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 14
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_proxy_node_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::proxy_tools::proxy_node_plugin::node_plugin::__export_proxy_tools_proxy_node_plugin_node_plugin_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::proxy_tools::proxy_node_plugin::node_plugin);
    };
}
#[doc(inline)]
pub(crate) use __export_proxy_node_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:proxy-tools:proxy-node-plugin@0.1.0:proxy-node-plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1278] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xf6\x08\x01A\x02\x01\
A\x02\x01B4\x01r\x02\x04names\x05values\x04\0\x0erequest-header\x03\0\0\x01r\x02\
\x03keys\x05values\x04\0\x0dcontext-entry\x03\0\x02\x01r\x01\x04jsons\x04\0\x0dj\
son-document\x03\0\x04\x01q\x02\x03set\x01\x03\0\x06remove\x01s\0\x04\0\x10conte\
xt-patch-op\x03\0\x06\x01p\x07\x01r\x01\x03ops\x08\x04\0\x0dcontext-patch\x03\0\x09\
\x01q\x03\x03set\x01\x01\0\x06append\x01\x01\0\x06remove\x01s\0\x04\0\x09header-\
op\x03\0\x0b\x01r\x01\x04paths\x04\0\x0cpath-rewrite\x03\0\x0d\x01r\x01\x04ports\
\x04\0\x09next-port\x03\0\x0f\x01q\x04\x05debug\0\0\x04info\0\0\x04warn\0\0\x05e\
rror\0\0\x04\0\x09log-level\x03\0\x11\x01r\x02\x05level\x12\x07messages\x04\0\x09\
log-entry\x03\0\x13\x01q\x03\x03log\0\0\x02fs\0\0\x07network\0\0\x04\0\x0fcapabi\
lity-kind\x03\0\x15\x01ks\x01r\x04\x04kind\x16\x08required\x7f\x05scope\x17\x0bd\
escriptions\x04\0\x16capability-declaration\x03\0\x18\x01r\x03\x04kind\x16\x07al\
lowed\x7f\x05scope\x17\x04\0\x10capability-grant\x03\0\x1a\x01ps\x01k\x05\x01p\x19\
\x01r\x07\x02ids\x04names\x07versions\x0bdescriptions\x16supported-output-ports\x1c\
\x1bdefault-config-schema-hints\x1d\x0ccapabilities\x1e\x04\0\x0fplugin-manifest\
\x03\0\x1f\x01p\x1b\x01r\x03\x08manifest\x20\x06grants!\x06config\x1d\x04\0\x0bn\
ode-config\x03\0\"\x01p\x01\x01p\x03\x01r\x07\x0erequest-methods\x0ccurrent-path\
s\x0frequest-headers$\x10workflow-context%\x14selected-provider-ids\x11selected-\
model-ids\x0bnode-config#\x04\0\x0dexecute-input\x03\0&\x01k\x0a\x01p\x0c\x01k\x0e\
\x01k\x10\x01p\x14\x01r\x05\x0dcontext-patch(\x0aheader-ops)\x0cpath-rewrite*\x09\
next-port+\x04logs,\x04\0\x0eexecute-output\x03\0-\x01q\x03\x06denied\x01s\0\x0d\
invalid-input\x01s\0\x06failed\x01s\0\x04\0\x0dexecute-error\x03\0/\x01j\x01.\x01\
0\x01@\x01\x05input'\01\x04\0\x07execute\x012\x04\0/proxy-tools:proxy-node-plugi\
n/node-plugin@0.1.0\x05\0\x04\05proxy-tools:proxy-node-plugin/proxy-node-plugin@\
0.1.0\x04\0\x0b\x17\x01\0\x11proxy-node-plugin\x03\0\0\0G\x09producers\x01\x0cpr\
ocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
